prey:
  RABBIT:
    xp: 3
    coins: 5
  CHICKEN:
    xp: 1
    coins: 2

shop:
  - item: BONE
    name: "Bone"
    price: 10
    lore:
      - "A great bone to dig"
  - item: COOKED_BEEF
    name: "Steak"
    price: 15
    lore:
      - "Big meal"